fans_names = {
    'Pure Double Chow': 'Чистое двойное чоу',
    'Mixed Double Chow': 'Смешанное двойное чоу',
    'Short Straight': 'Короткий ряд',
    'Two Terminal Chows': 'Два терминальных чоу',
    'Pung of Terminals or Honors': 'Панг терминальных или благородных',
    'Melded Kong': 'Открытый конг',
    'One Voided Suit': 'Пропущенная масть',
    'No Honors': 'Без благородных',
    'Edge Wait': 'Крайнее ожидание',
    'Closed Wait': 'Закрытое ожидание',
    'Single Wait': 'Ожидание единственной',
    'Self-draw': 'Выигрыш со стены',
    'Flower Tiles': 'Цветок',
    'Dragon Pung': 'Панг драконов',
    'Prevalent Wind': 'Преимущественный ветер',
    'Seat Wind': 'Ветер места',
    'All Chows': 'Все чоу',
    'Double Pung': 'Двойной панг',
    'Two Concealed Pungs': 'Два закрытых панга',
    'Concealed Kong': 'Закрытый конг',
    'All Simples': 'Все простые',
    'Concealed Hand': 'Закрытая рука',
    'Tile Hog': 'Четыре врозь',
    'Two Melded Kongs': 'Два открытых конга',
    'Outside Hand': 'Внешняя рука',
    'Fully Concealed Hand': 'Полностью закрытая рука',
    'Last Tile': 'Последняя кость',
    'Two Dragon Pungs': 'Два панга драконов',
    'Mixed Shifted Chows': 'Смешанные смещенные чоу',
    'All Pungs': 'Все панги',
    'Half Flush': 'Пол-изобилия',
    'All Types': 'Все типы',
    'Melded Hand': 'Открытая рука',
    'Mixed Triple Chows': 'Смешанное тройное чоу',
    'Mixed Straight': 'Смешанный ряд',
    'Mixed Shifted Pungs': 'Смешанные смещенные панги',
    'Two Concealed Kongs': 'Два закрытых конга',
    'Last Tile Draw': 'Последняя кость со стены',
    'Last Tile Claim': 'Последний снос',
    'Out With Replacement Tile': 'Выигрыш замещающей костью',
    'Robbing the Kong': 'Ограбление конга',
    'Reversible Tiles': 'Симметричные кости',
    'Chicken Hand': 'Цыплячья рука',
    'Big Three Winds': 'Большие три ветра',
    'Knitted Straight': 'Переплетенный ряд',
    'Upper Four': 'Четыре верхних',
    'Lower Four': 'Четыре нижних',
    'Lesser Honors and Knitted Tiles': 'Малые благородные и переплетенные кости',
    'Pure Shifted Chows': 'Чистые смещенные чоу',
    'Pure Straight': 'Чистый ряд',
    'Three Suited Terminal Chows': 'Три масти и терминальные чоу',
    'Triple Pung': 'Тройной панг',
    'Three Concealed Pungs': 'Три закрытых панга',
    'All Fives': 'Все пятерки',
    'Pure Triple Chow': 'Чистое тройное чоу',
    'All Even Pungs': 'Все четные панги',
    'Pure Shifted Pungs': 'Чистые смещенные панги',
    'Seven Pairs': 'Семь пар',
    'Full Flush': 'Полное изобилие',
    'Upper Tiles': 'Верхние кости',
    'Middle Tiles': 'Средние кости',
    'Lower Tiles': 'Нижние кости',
    'Greater Honors and Knitted Tiles': 'Большие благородные и переплетенные кости',
    'Four Pure Shifted Chows': 'Четыре чистых смещенных чоу',
    'All Terminals and Honors': 'Все терминальные и благородные',
    'Three Kongs': 'Три конга',
    'Quadruple Chow': 'Четверное чоу',
    'Four Pure Shifted Pungs': 'Четыре чистых смещенных панга',
    'Little Four Winds': 'Малые четыре ветра',
    'Little Three Dragons': 'Малые три ветра',
    'All Honors': 'Все благородные',
    'Pure Terminal Chows': 'Чистые терминальные чоу',
    'All Terminals': 'Все терминальные',
    'Four Concealed Pungs': 'Четыре закрытых панга',
    'Big Four Winds': 'Большие четыре ветра',
    'Big Three Dragons': 'Большие четыре дракона',
    'Four Kongs': 'Четыре конга',
    'Seven Shifted Pairs': 'Семь смещенных пар',
    'All Green': 'Все зеленые',
    'Nine Gates': 'Девять врат',
    'Thirteen Orphans': 'Тринадцать сирот'
}

def get_fan_name(name):
    return fans_names[name]
